---
control_info:
  manual_thruster_update_hz: 20
  stabilization:
    rate: 25
    gains:
      x:
        kp: 0
        ki: 0
        kd: 0
      y:
        kp: 0
        ki: 0
        kd: 0
      z:
        kp: 10
        ki: 0
        kd: 0.2
      roll:
        kp: 0
        ki: 0
        kd: 0
      pitch:
        kp: 0
        ki: 0
        kd: 0
      yaw:
        kp: 0.7
        ki: 0.15
        kd: 0.2
    control_mode:
      x: manual  # Options: manual, pid
      y: manual  # Options: manual, pid
      z: pid     # Options: manual, pid
      roll: pid  # Options: manual, pid
      pitch: pid # Options: manual, pid
      yaw: pid   # Options: manual, pid
